on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt-get install -y libncurses5

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - name: Cache
        uses: actions/cache@v3
        with:
            path: build
            key: build-${{ runner.os }}-${{ github.run_id }}
            restore-keys: |
                build-${{ runner.os }}-

      - name: Run tests
        run: ./ci.sh
        shell: bash
